// Package api provides the main ARK SDK API interface for accessing all ARK services
// Code generated by genservices; DO NOT EDIT.
// Automatically generated Ark API for all SDK services.
// Each service can define a module init to register its config alongside a ServiceGenerator function
// in the ARK SDK Golang. This package serves as the central entry point for interacting
// with various ARK services including SIA, SecHub, PCloud, Identity, and other components.
//
// The ArkAPI struct acts as a service factory and registry, managing authenticators,
// service instances, and configuration profiles. It provides lazy loading of services,
// meaning services are only instantiated when first accessed, and subsequent calls
// return the cached instance.
//
// Key features:
//   - Centralized access to all ARK services
//   - Lazy loading and caching of service instances
//   - Authenticator management and distribution to services
//   - Profile-based configuration management
//   - Service dependency injection with authenticators
//   - Consistent error handling across all services
//
// The API supports multiple authenticators that are automatically distributed to
// services based on their configuration requirements. Each service specifies
// required and optional authenticators, and the API ensures the appropriate
// authenticators are provided during service initialization.
//
// Example:
//
//	// Create authenticators
//	ispAuth := &auth.ArkISPAuth{...}
//	authenticators := []auth.ArkAuth{ispAuth}
//
//	// Create API instance
//	api, err := NewArkAPI(authenticators, nil) // nil uses default profile
//	if err != nil {
//		// handle error
//	}
//
//	// Access services (lazy loaded)
//	ssoService, err := api.SiaSso()
//	if err != nil {
//		// handle error
//	}
//
//	// Get specific authenticator
//	auth, err := api.Authenticator("isp")
//	if err != nil {
//		// handle error
//	}
package api

import (
	"fmt"

	"github.com/cyberark/ark-sdk-golang/pkg/auth"
	"github.com/cyberark/ark-sdk-golang/pkg/models"
	"github.com/cyberark/ark-sdk-golang/pkg/profiles"
	"github.com/cyberark/ark-sdk-golang/pkg/services"

	cmgr "github.com/cyberark/ark-sdk-golang/pkg/services/cmgr"
	directories "github.com/cyberark/ark-sdk-golang/pkg/services/identity/directories"
	roles "github.com/cyberark/ark-sdk-golang/pkg/services/identity/roles"
	users "github.com/cyberark/ark-sdk-golang/pkg/services/identity/users"
	accounts "github.com/cyberark/ark-sdk-golang/pkg/services/pcloud/accounts"
	safes "github.com/cyberark/ark-sdk-golang/pkg/services/pcloud/safes"
	configuration "github.com/cyberark/ark-sdk-golang/pkg/services/sechub/configuration"
	filters "github.com/cyberark/ark-sdk-golang/pkg/services/sechub/filters"
	scans "github.com/cyberark/ark-sdk-golang/pkg/services/sechub/scans"
	secrets "github.com/cyberark/ark-sdk-golang/pkg/services/sechub/secrets"
	secretstores "github.com/cyberark/ark-sdk-golang/pkg/services/sechub/secretstores"
	serviceinfo "github.com/cyberark/ark-sdk-golang/pkg/services/sechub/serviceinfo"
	syncpolicies "github.com/cyberark/ark-sdk-golang/pkg/services/sechub/syncpolicies"
	access "github.com/cyberark/ark-sdk-golang/pkg/services/sia/access"
	db "github.com/cyberark/ark-sdk-golang/pkg/services/sia/db"
	k8s "github.com/cyberark/ark-sdk-golang/pkg/services/sia/k8s"
	dbsecrets "github.com/cyberark/ark-sdk-golang/pkg/services/sia/secrets/db"
	vmsecrets "github.com/cyberark/ark-sdk-golang/pkg/services/sia/secrets/vm"
	sshca "github.com/cyberark/ark-sdk-golang/pkg/services/sia/sshca"
	sso "github.com/cyberark/ark-sdk-golang/pkg/services/sia/sso"
	db2 "github.com/cyberark/ark-sdk-golang/pkg/services/sia/workspaces/db"
	targetsets "github.com/cyberark/ark-sdk-golang/pkg/services/sia/workspaces/targetsets"
	sm "github.com/cyberark/ark-sdk-golang/pkg/services/sm"
	uap "github.com/cyberark/ark-sdk-golang/pkg/services/uap"
	sca "github.com/cyberark/ark-sdk-golang/pkg/services/uap/sca"
	db3 "github.com/cyberark/ark-sdk-golang/pkg/services/uap/sia/db"
	vm "github.com/cyberark/ark-sdk-golang/pkg/services/uap/sia/vm"
)

// ArkAPI wraps different API functionality of Ark Services.
//
// ArkAPI serves as the central entry point and service factory for all ARK services.
// It manages authenticators, service instances, and configuration profiles, providing
// a unified interface for accessing various ARK components including SIA, SecHub,
// PCloud, Identity, and other services.
//
// The struct implements lazy loading for services - each service is only instantiated
// when first accessed through its corresponding method. Subsequent calls return the
// cached instance, ensuring efficient resource usage and consistent service state.
//
// Service creation follows a dependency injection pattern where authenticators are
// automatically distributed to services based on their configuration requirements.
// Each service specifies required and optional authenticators, and ArkAPI ensures
// the appropriate authenticators are provided during initialization.
type ArkAPI struct {
	authenticators []auth.ArkAuth
	services       map[string]*services.ArkService
	profile        *models.ArkProfile
}

// NewArkAPI creates a new ArkAPI instance with the provided authenticators and profile.
//
// Initializes a new ArkAPI instance that serves as the central access point for all
// ARK services. The instance manages the provided authenticators and distributes them
// to services as needed. If no profile is provided (nil), the default profile is
// loaded automatically.
//
// The services map is initialized empty and services are created lazily when first
// accessed through their respective getter methods. This approach ensures optimal
// resource usage and faster startup times.
//
// Parameters:
//   - authenticators: Slice of authenticators to be used by services. Each service
//     will receive the authenticators it requires based on its configuration
//   - profile: Configuration profile to use. If nil, the default profile is loaded
//     automatically using the default profile loader
//
// Returns a pointer to the initialized ArkAPI instance, or an error if the default
// profile cannot be loaded when profile is nil.
//
// Example:
//
//	// With explicit profile
//	profile := &models.ArkProfile{...}
//	api, err := NewArkAPI(authenticators, profile)
//
//	// With default profile (recommended)
//	api, err := NewArkAPI(authenticators, nil)
//	if err != nil {
//		// handle profile loading error
//	}
func NewArkAPI(authenticators []auth.ArkAuth, profile *models.ArkProfile) (*ArkAPI, error) {
	var err error
	if profile == nil {
		profile, err = (*profiles.DefaultProfilesLoader()).LoadDefaultProfile()
		if err != nil {
			return nil, err
		}
	}
	return &ArkAPI{
		authenticators: authenticators,
		services:       make(map[string]*services.ArkService),
		profile:        profile,
	}, nil
}

// loadServiceAuthenticators filters and returns authenticators required by a service configuration.
//
// This internal method processes the API's authenticator collection and returns only
// those authenticators that are required or optional for the specified service.
// Required authenticators are processed first, followed by optional authenticators.
//
// The method ensures that services receive only the authenticators they need,
// following the dependency injection pattern. This approach provides better
// security isolation and cleaner service initialization.
//
// Parameters:
//   - config: Service configuration specifying required and optional authenticator names
//
// Returns a slice of authenticators that match the service's requirements.
// If no matching authenticators are found, returns an empty slice.
func (api *ArkAPI) loadServiceAuthenticators(config services.ArkServiceConfig) []auth.ArkAuth {
	var authenticators []auth.ArkAuth
	for _, authenticator := range api.authenticators {
		for _, name := range config.RequiredAuthenticatorNames {
			if authenticator.AuthenticatorName() == name {
				authenticators = append(authenticators, authenticator)
			}
		}
	}
	for _, authenticator := range api.authenticators {
		for _, name := range config.OptionalAuthenticatorNames {
			if authenticator.AuthenticatorName() == name {
				authenticators = append(authenticators, authenticator)
			}
		}
	}
	return authenticators
}

// Authenticator returns the authenticator with the specified name from the ArkAPI instance.
//
// Searches through the API's authenticator collection and returns the first
// authenticator that matches the specified name. This method provides access
// to specific authenticators for custom operations or debugging purposes.
//
// The search is case-sensitive and matches the exact authenticator name as
// returned by the authenticator's AuthenticatorName() method.
//
// Parameters:
//   - authenticatorName: The exact name of the authenticator to retrieve
//
// Returns the matching authenticator, or an error if no authenticator with
// the specified name is found.
//
// Example:
//
//	ispAuth, err := api.Authenticator("isp")
//	if err != nil {
//		// handle authenticator not found
//	}
//	// use ispAuth for custom operations
func (api *ArkAPI) Authenticator(authenticatorName string) (auth.ArkAuth, error) {
	for _, authenticator := range api.authenticators {
		if authenticator.AuthenticatorName() == authenticatorName {
			return authenticator, nil
		}
	}
	return nil, fmt.Errorf("%s is not supported or not found", authenticatorName)
}

// Profile returns the profile associated with the ArkAPI instance.
//
// Provides access to the configuration profile that was set during API initialization.
// The profile contains environment-specific settings, endpoints, and other configuration
// parameters used by the various ARK services.
//
// The returned profile is the same instance that was either explicitly provided to
// NewArkAPI or automatically loaded as the default profile when nil was passed.
//
// Returns a pointer to the ArkProfile instance. The profile is never nil for a
// properly initialized ArkAPI instance.
//
// Example:
//
//	profile := api.Profile()
//	fmt.Printf("Using profile: %s\n", profile.ProfileName)
func (api *ArkAPI) Profile() *models.ArkProfile {
	return api.profile
}

func (api *ArkAPI) Cmgr() (*cmgr.ArkCmgrService, error) {
	if serviceIfs, ok := api.services[cmgr.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*cmgr.ArkCmgrService), nil
	}
	service, err := cmgr.ServiceGenerator(api.loadServiceAuthenticators(cmgr.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[cmgr.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) IdentityDirectories() (*directories.ArkIdentityDirectoriesService, error) {
	if serviceIfs, ok := api.services[directories.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*directories.ArkIdentityDirectoriesService), nil
	}
	service, err := directories.ServiceGenerator(api.loadServiceAuthenticators(directories.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[directories.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) IdentityRoles() (*roles.ArkIdentityRolesService, error) {
	if serviceIfs, ok := api.services[roles.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*roles.ArkIdentityRolesService), nil
	}
	service, err := roles.ServiceGenerator(api.loadServiceAuthenticators(roles.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[roles.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) IdentityUsers() (*users.ArkIdentityUsersService, error) {
	if serviceIfs, ok := api.services[users.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*users.ArkIdentityUsersService), nil
	}
	service, err := users.ServiceGenerator(api.loadServiceAuthenticators(users.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[users.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) PcloudAccounts() (*accounts.ArkPCloudAccountsService, error) {
	if serviceIfs, ok := api.services[accounts.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*accounts.ArkPCloudAccountsService), nil
	}
	service, err := accounts.ServiceGenerator(api.loadServiceAuthenticators(accounts.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[accounts.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) PcloudSafes() (*safes.ArkPCloudSafesService, error) {
	if serviceIfs, ok := api.services[safes.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*safes.ArkPCloudSafesService), nil
	}
	service, err := safes.ServiceGenerator(api.loadServiceAuthenticators(safes.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[safes.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) SechubConfiguration() (*configuration.ArkSecHubConfigurationService, error) {
	if serviceIfs, ok := api.services[configuration.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*configuration.ArkSecHubConfigurationService), nil
	}
	service, err := configuration.ServiceGenerator(api.loadServiceAuthenticators(configuration.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[configuration.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) SechubFilters() (*filters.ArkSecHubFiltersService, error) {
	if serviceIfs, ok := api.services[filters.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*filters.ArkSecHubFiltersService), nil
	}
	service, err := filters.ServiceGenerator(api.loadServiceAuthenticators(filters.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[filters.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) SechubScans() (*scans.ArkSecHubScansService, error) {
	if serviceIfs, ok := api.services[scans.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*scans.ArkSecHubScansService), nil
	}
	service, err := scans.ServiceGenerator(api.loadServiceAuthenticators(scans.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[scans.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) SechubSecrets() (*secrets.ArkSecHubSecretsService, error) {
	if serviceIfs, ok := api.services[secrets.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*secrets.ArkSecHubSecretsService), nil
	}
	service, err := secrets.ServiceGenerator(api.loadServiceAuthenticators(secrets.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[secrets.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) SechubSecretstores() (*secretstores.ArkSecHubSecretStoresService, error) {
	if serviceIfs, ok := api.services[secretstores.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*secretstores.ArkSecHubSecretStoresService), nil
	}
	service, err := secretstores.ServiceGenerator(api.loadServiceAuthenticators(secretstores.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[secretstores.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) SechubServiceinfo() (*serviceinfo.ArkSecHubServiceInfoService, error) {
	if serviceIfs, ok := api.services[serviceinfo.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*serviceinfo.ArkSecHubServiceInfoService), nil
	}
	service, err := serviceinfo.ServiceGenerator(api.loadServiceAuthenticators(serviceinfo.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[serviceinfo.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) SechubSyncpolicies() (*syncpolicies.ArkSecHubSyncPoliciesService, error) {
	if serviceIfs, ok := api.services[syncpolicies.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*syncpolicies.ArkSecHubSyncPoliciesService), nil
	}
	service, err := syncpolicies.ServiceGenerator(api.loadServiceAuthenticators(syncpolicies.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[syncpolicies.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) SiaAccess() (*access.ArkSIAAccessService, error) {
	if serviceIfs, ok := api.services[access.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*access.ArkSIAAccessService), nil
	}
	service, err := access.ServiceGenerator(api.loadServiceAuthenticators(access.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[access.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) SiaDb() (*db.ArkSIADBService, error) {
	if serviceIfs, ok := api.services[db.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*db.ArkSIADBService), nil
	}
	service, err := db.ServiceGenerator(api.loadServiceAuthenticators(db.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[db.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) SiaK8s() (*k8s.ArkSIAK8SService, error) {
	if serviceIfs, ok := api.services[k8s.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*k8s.ArkSIAK8SService), nil
	}
	service, err := k8s.ServiceGenerator(api.loadServiceAuthenticators(k8s.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[k8s.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) SiaSecretsDb() (*dbsecrets.ArkSIASecretsDBService, error) {
	if serviceIfs, ok := api.services[dbsecrets.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*dbsecrets.ArkSIASecretsDBService), nil
	}
	service, err := dbsecrets.ServiceGenerator(api.loadServiceAuthenticators(dbsecrets.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[dbsecrets.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) SiaSecretsVm() (*vmsecrets.ArkSIASecretsVMService, error) {
	if serviceIfs, ok := api.services[vmsecrets.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*vmsecrets.ArkSIASecretsVMService), nil
	}
	service, err := vmsecrets.ServiceGenerator(api.loadServiceAuthenticators(vmsecrets.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[vmsecrets.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) SiaSshca() (*sshca.ArkSIASSHCAService, error) {
	if serviceIfs, ok := api.services[sshca.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*sshca.ArkSIASSHCAService), nil
	}
	service, err := sshca.ServiceGenerator(api.loadServiceAuthenticators(sshca.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[sshca.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) SiaSso() (*sso.ArkSIASSOService, error) {
	if serviceIfs, ok := api.services[sso.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*sso.ArkSIASSOService), nil
	}
	service, err := sso.ServiceGenerator(api.loadServiceAuthenticators(sso.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[sso.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) SiaWorkspacesDb() (*db2.ArkSIAWorkspacesDBService, error) {
	if serviceIfs, ok := api.services[db2.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*db2.ArkSIAWorkspacesDBService), nil
	}
	service, err := db2.ServiceGenerator(api.loadServiceAuthenticators(db2.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[db2.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) SiaWorkspacesTargetsets() (*targetsets.ArkSIAWorkspacesTargetSetsService, error) {
	if serviceIfs, ok := api.services[targetsets.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*targetsets.ArkSIAWorkspacesTargetSetsService), nil
	}
	service, err := targetsets.ServiceGenerator(api.loadServiceAuthenticators(targetsets.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[targetsets.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) Sm() (*sm.ArkSMService, error) {
	if serviceIfs, ok := api.services[sm.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*sm.ArkSMService), nil
	}
	service, err := sm.ServiceGenerator(api.loadServiceAuthenticators(sm.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[sm.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) Uap() (*uap.ArkUAPService, error) {
	if serviceIfs, ok := api.services[uap.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*uap.ArkUAPService), nil
	}
	service, err := uap.ServiceGenerator(api.loadServiceAuthenticators(uap.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[uap.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) UapDb() (*db3.ArkUAPSIADBService, error) {
	if serviceIfs, ok := api.services[db3.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*db3.ArkUAPSIADBService), nil
	}
	service, err := db3.ServiceGenerator(api.loadServiceAuthenticators(db3.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[db3.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) UapSca() (*sca.ArkUAPSCAService, error) {
	if serviceIfs, ok := api.services[sca.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*sca.ArkUAPSCAService), nil
	}
	service, err := sca.ServiceGenerator(api.loadServiceAuthenticators(sca.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[sca.ServiceConfig.ServiceName] = &baseService
	return service, nil
}

func (api *ArkAPI) UapVm() (*vm.ArkUAPSIAVMService, error) {
	if serviceIfs, ok := api.services[vm.ServiceConfig.ServiceName]; ok {
		return (*serviceIfs).(*vm.ArkUAPSIAVMService), nil
	}
	service, err := vm.ServiceGenerator(api.loadServiceAuthenticators(vm.ServiceConfig)...)
	if err != nil {
		return nil, err
	}
	var baseService services.ArkService = service
	api.services[vm.ServiceConfig.ServiceName] = &baseService
	return service, nil
}
